id: P010542
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS16714
  title: བསྡུས་གཞུང་ལུང་རིགས་ཉི་མའི་ཟུར་བཀོལ་བློ་གསལ་བྱིས་པའི་འཇུག་ངོགས།
  author: ''
  volumes:
    c874466ca8c04bc2be1d232a7a821e34:
      image_group_id: I8LS16730
      title: ''
      volume_number: 1
      total_pages: 92
      base_file: v001.txt
